# Example .trivyignore.yaml - more structured than .trivyignore
vulnerabilities:
  - id: "CVE-2021-44228"
    paths:
      - "vendor/**"
    statement: "Log4j vulnerability in vendor dependencies - will be updated in next release"
    
  - id: "AVD-KSV-0121"
    paths:
      - "k8s/dev/**"
    statement: "Development environment - security context not required"

misconfigurations:
  - id: "AVD-KSV-0014"
    paths:
      - "docker/dev.dockerfile"
    statement: "Development dockerfile - root user acceptable"
    
  - id: "AVD-DS-0002"
    paths:
      - "charts/*/templates/*.yaml"
    statement: "Helm templates - resource limits set via values"
